/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Alfaiataria;

import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author 23162858
 */
public class Login extends javax.swing.JFrame {

    String dir, b, c;
    AppFunc nomep;
    Vector<String> cp;

    public Login() {
        initComponents();
        nomep = new AppFunc();
        cp = new Vector<String>();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        login = new javax.swing.JTextField();
        KeyboardFocusManager.getCurrentKeyboardFocusManager()
        .addKeyEventDispatcher(new KeyEventDispatcher() {
            @Override
            public boolean dispatchKeyEvent(KeyEvent event) {
                if (event.getID() == KeyEvent.KEY_PRESSED
                    && event.getKeyCode() == KeyEvent.VK_ENTER) {
                    dir = "C:\\ProgramData\\MySQL\\MySQL Server 5.7\\Uploads\\LoginSenha.csv";

                    LeitorCSV arq = new LeitorCSV();
                    b = login.getText();
                    c = senha.getText();
                    boolean a = arq.abreCSV(dir, b, c);
                    if (a) {
                        new Principal().setVisible(true);
                        dispose();
                    } else {
                        JOptionPane.showInputDialog("Usúario e/ou senha incorretos");
                    }
                    return true;
                }
                return false;
            }
        });
        javax.swing.JButton Entrar = new javax.swing.JButton();
        OlhoQueTudoVê = new javax.swing.JToggleButton();
        senha = new javax.swing.JPasswordField();
        registro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(lista);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 55));
        jPanel1.setLayout(null);

        login.setBackground(new java.awt.Color(0,0,0,0));
        login.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        login.setActionCommand("<Not Set>");
        login.setAlignmentX(2.0F);
        login.setAlignmentY(2.0F);
        login.setBorder(null);
        login.setMargin(new java.awt.Insets(4, 8, 4, 8));
        login.setMinimumSize(new java.awt.Dimension(3, 16));
        login.setPreferredSize(new java.awt.Dimension(3, 16));
        login.setSelectionStart(3);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login);
        login.setBounds(194, 274, 250, 20);

        Entrar.setBackground(new java.awt.Color(0,0,0,0));
        Entrar.setForeground(new java.awt.Color(139, 64, 13));
        Entrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\afons\\Documents\\NetBeansProjects\\Alfaiatari\\Imagens\\Login.png")); // NOI18N
        Entrar.setBorder(null);
        Entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarActionPerformed(evt);
            }
        });
        Entrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EntrarKeyReleased(evt);
            }
        });
        jPanel1.add(Entrar);
        Entrar.setBounds(190, 440, 160, 40);

        OlhoQueTudoVê.setBackground(new java.awt.Color(0,0,0,0));
        OlhoQueTudoVê.setIcon(new javax.swing.ImageIcon("C:\\Users\\afons\\Documents\\NetBeansProjects\\Alfaiatari\\Imagens\\Senha_nao-removebg-preview.png")); // NOI18N
        OlhoQueTudoVê.setBorder(null);
        OlhoQueTudoVê.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OlhoQueTudoVê.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\afons\\Documents\\NetBeansProjects\\Alfaiatari\\Imagens\\Senha_sim-removebg-preview.png")); // NOI18N
        OlhoQueTudoVê.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OlhoQueTudoVêActionPerformed(evt);
            }
        });
        jPanel1.add(OlhoQueTudoVê);
        OlhoQueTudoVê.setBounds(410, 330, 30, 20);

        senha.setBackground(new java.awt.Color(0,0,0,0));
        senha.setActionCommand("<Not Set>");
        senha.setBorder(null);
        senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaActionPerformed(evt);
            }
        });
        jPanel1.add(senha);
        senha.setBounds(194, 320, 250, 40);

        registro.setBackground(new java.awt.Color(0,0,0,0));
        registro.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        registro.setForeground(new java.awt.Color(139, 64, 13));
        registro.setText("Registre-se");
        registro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroActionPerformed(evt);
            }
        });
        jPanel1.add(registro);
        registro.setBounds(190, 490, 160, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\afons\\Documents\\NetBeansProjects\\Alfaiatari\\Imagens\\Tela Login (1).png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-3, -4, 800, 610);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarActionPerformed

//         dir = "C:\\Users\\Audrey\\Documents\\Banco Alfaiataria\\LoginSenha.csv";
//        dir = "C:\\ProgramData\\MySQL\\MySQL Server 5.7\\Uploads\\LoginSenha.csv";
        dir = "D:\\\\wamp64\\\\tmp\\\\LoginSenha.csv";
        

        LeitorCSV arq = new LeitorCSV();
        b = login.getText();
        c = senha.getText();
        boolean a = arq.abreCSV(dir, b, c);
        if (a) {
            new Principal().setVisible(true);
            dispose();
        } else {
            JOptionPane.showInputDialog("Usúario e/ou senha incorretos");
        }

    }//GEN-LAST:event_EntrarActionPerformed
//   if(email=="admin"&&senha=="admin"){
    private void registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroActionPerformed
        new CadastroLogin().setVisible(true);
        dispose();

    }//GEN-LAST:event_registroActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaActionPerformed

    private void EntrarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EntrarKeyReleased
        KeyboardFocusManager.getCurrentKeyboardFocusManager()
                .addKeyEventDispatcher(new KeyEventDispatcher() {
                    @Override
                    public boolean dispatchKeyEvent(KeyEvent event) {
                        if (event.getID() == KeyEvent.KEY_RELEASED
                                && event.getKeyCode() == KeyEvent.VK_ENTER) {
                            dir = "D:\\\\wamp64\\\\tmp\\\\LoginSenha.csv";
//                            dir = "C:\\ProgramData\\MySQL\\MySQL Server 5.7\\Uploads\\LoginSenha.csv";

                            LeitorCSV arq = new LeitorCSV();
                            b = login.getText();
                            c = senha.getText();
                            boolean a = arq.abreCSV(dir, b, c);
                            if (a) {
                                new Principal().setVisible(true);
                                dispose();
                            } else {
                                JOptionPane.showInputDialog("Usúario e/ou senha incorretos");
                            }
                            return true;
                        }
                        return false;
                    }
                });
    }//GEN-LAST:event_EntrarKeyReleased

    private void OlhoQueTudoVêActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OlhoQueTudoVêActionPerformed
        if (OlhoQueTudoVê.isSelected())
            senha.setEchoChar((char) 0);
        else
            senha.setEchoChar('*');
    }//GEN-LAST:event_OlhoQueTudoVêActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton OlhoQueTudoVê;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lista;
    private javax.swing.JTextField login;
    private javax.swing.JButton registro;
    private javax.swing.JPasswordField senha;
    // End of variables declaration//GEN-END:variables
}
