/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Conexão;

import java.util.Vector;
import javax.swing.JOptionPane;
import Conexão.GetSet;
import java.sql.SQLException;
import Conexão.Usuario;
import java.sql.ResultSet;

/**
 *
 * @author 23162858
 */
public class Login2 extends javax.swing.JFrame {
String dir,b,c;
//    AppFunc nomep;
    Vector<String> cp;

    public Login2() {
        initComponents();
//        nomep = new AppFunc();
//        cp = new Vector<String>();
        dir = "D:\\wamp64\\tmp\\LoginSenha.csv";
        
    }
            

        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        txtlogin = new javax.swing.JTextField();
        Entrar = new javax.swing.JButton();
        txtsenha = new javax.swing.JPasswordField();
        registro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(lista);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 55));
        jPanel1.setLayout(null);

        txtlogin.setBackground(new java.awt.Color(0,0,0,0));
        txtlogin.setBorder(null);
        txtlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtloginActionPerformed(evt);
            }
        });
        jPanel1.add(txtlogin);
        txtlogin.setBounds(200, 270, 240, 30);

        Entrar.setBackground(new java.awt.Color(0,0,0,0));
        Entrar.setForeground(new java.awt.Color(139, 64, 13));
        Entrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\afons\\Documents\\NetBeansProjects\\Alfaiatari\\Imagens\\Login.png")); // NOI18N
        Entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarActionPerformed(evt);
            }
        });
        jPanel1.add(Entrar);
        Entrar.setBounds(190, 440, 160, 40);

        txtsenha.setBackground(new java.awt.Color(0,0,0,0));
        txtsenha.setBorder(null);
        txtsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsenhaActionPerformed(evt);
            }
        });
        jPanel1.add(txtsenha);
        txtsenha.setBounds(200, 320, 240, 40);

        registro.setBackground(new java.awt.Color(0,0,0,0));
        registro.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        registro.setForeground(new java.awt.Color(139, 64, 13));
        registro.setText("Registre-se");
        registro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroActionPerformed(evt);
            }
        });
        jPanel1.add(registro);
        registro.setBounds(190, 490, 160, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\afons\\Documents\\NetBeansProjects\\Alfaiatari\\Imagens\\Tela Login (1).png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-3, -4, 800, 610);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarActionPerformed
        String login, senha;
        login = txtlogin.getText();
        senha = txtsenha.getText();
        GetSet us = new GetSet();
        us.setLogin(login);
        us.setSenha(senha);
        Usuario us2 = new Usuario();
        ResultSet rsus = us2.autenticacao(us);
        if(us2.next()){
            
        }else{
            JOptionPane.showMessageDialog(null, "Usuário ou Senha inválida");
        }
    }//GEN-LAST:event_EntrarActionPerformed
//   if(email=="admin"&&senha=="admin"){
    private void registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroActionPerformed
//        new Cadastro().setVisible(true);

    }//GEN-LAST:event_registroActionPerformed

    private void txtsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsenhaActionPerformed

    private void txtloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Entrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lista;
    private javax.swing.JButton registro;
    private javax.swing.JTextField txtlogin;
    private javax.swing.JPasswordField txtsenha;
    // End of variables declaration//GEN-END:variables
}
